version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DEBUG_SECRET_VALUE=${DEBUG_SECRET_VALUE:-my-secret-key-123}
      - FLAG=${FLAG:-YCTF{test_flag_value}}
      - BROBOT_SECRET=${BROBOT_SECRET:-secret}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN:-localhost}
      # Public environment variables (available in browser)
      - NODE_ENV=production
    restart: unless-stopped
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s